### ISSUE TITLE
App not meeting Progressive Web App requirements according to Lighthouse

### ISSUE THREAD

**Issue by aaronfand** [Call-for-Code/Liquid-Prep#77]
**Describe the bug**
App not meeting Progressive Web App requirements according to Lighthouse

**To reproduce**
1. Bring up web app
2. Open Lighthouse from Developer Tools (must have loaded as extension)
3. Run a report

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/667779/112862685-a0ea0300-907b-11eb-87cc-f561fcefff09.png)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: Chrome

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by Gaurav-Ramakrishna** [comment]
@aaronfand looks like the service worker does not work with Angular's **`ng serve`** as it requires HTTPS. Therefore Lighthouse is complaining App is not meeting Progressive Web App requirements.
Instead, if you run the App with **`http-server`** for the service worker to work locally, Lighthouse will validate the PWA aspects of the App.

Steps to run the App on `http-server` and validate App's PWA aspects in Lighthouse,
1. Install [http-server](https://www.npmjs.com/package/http-server)
2. Open terminal/CMD in path `~Liquid-Prep/liquid-prep-app`.
3. Install App dependencies by executing `npm install`.
4. Build App by executing command `ng build --prod` or `npm run build-prod`.
5. Navigate to path `~Liquid-Prep/liquid-prep-app/dist/liquid-prep-app`.
6. Run the App on **`http-server`** by executing the command `http-server -o`.
7. Now open the chrome developer tool and generate a report in Lighthouse and you will see PWA report similar to the attached below image.
![image](https://user-images.githubusercontent.com/60436767/113043112-fac8f680-9169-11eb-803d-99fe7b77f94a.png)

**Comment by aaronfand** [comment]
Steps to run the App on http-server and validate App's PWA aspects in Lighthouse,
- Install **http-server-spa**
- Open terminal/CMD in path **~Liquid-Prep/liquid-prep-app**
- Install App dependencies by executing **npm install**.
- Build App by executing command **ng build --prod** or **npm run build-prod**.
- Run App by executing the command **http-server-spa dist/liquid-prep-app/ index.html 3800**
- Now open the chrome and navigate to **http://localhost:3800**
- Open Chrome developer tool and go to **Lighthouse** tab
- Click **Generate Report** button in Lighthouse and wait
- Eventually you will see PWA report similar to the attached below image.
![image](https://user-images.githubusercontent.com/667779/113193882-15f93c00-9226-11eb-9dda-0dc6f817cbd8.png)

**Comment by Gaurav-Ramakrishna** [comment]
Closing the issue as the app meets PWA requirements when deployed on `http-server` locally as described in previous comments and in [production on IBM Cloud](https://github.com/Call-for-Code/Liquid-Prep/tree/master/liquid-prep-app#deploy-app-in-IBM-Cloud-Object-storage)
