### ISSUE TITLE
Add Linux Foundation footer to liquidprep.org

### ISSUE THREAD

**Issue by krook** [Call-for-Code/Liquid-Prep#87]
We need to add a footer to the bottom of the web page, similar to this:

> Liquid Prep is a Call for Code® with The Linux Foundation project. Copyright © 2020-2021 Liquid Prep a Series of LF Projects, LLC. For web site terms of use, trademark policy and general project policies please see www.lfprojects.org.

Also, I see it's hosted on Wix. We could make the site itself open source and publish it through GitHub Pages.

**Comment by Gaurav-Ramakrishna** [comment]
The [Liquid Prep](https://www.liquidprep.org/) footer has been updated.

**Comment by krook** [comment]
Thanks Gaurav. We'll handle the access and hosting issues separately.
